### ISSUE TITLE
Datalogic SDK

### ISSUE THREAD

**Issue by olfried** [datalogic/android-sdk-addon#1]
Hi,
i am trying to install the Datalogic SDK as described on this page: 
https://datalogic.github.io/quick-start/android-studio.html

Unfortunately it fails. I don't see the Datalogic SDK after adding 
https://datalogic.github.io/android-sdk-addon/addon.xml.

I wonder if this has something to do with teh version or something else.

However. There is no one to contact on the page https://datalogic.github.io/
Even social media links are broken... :-)

I wonder if this is the right place to fix this problem. Or can you help me?

Sincerely
Olaf

**Comment by guidodavide** [comment]
Hi olfried,

I tried personally on Android Studio 2.3.3, after cleaning up any trace of Datalogic SDK.
And it worked.

After adding the URL in the right panel "**SDK Update Sites**", you must click on "_**Show Package Details**_" (found in the "**SDK Platforms**" panel).
As shown here: [picture](http://datalogic.github.io/images/install-sdk-as-checkbox.png)

Currently, the Add-on is **_not_** shown _**solely**_ for platform 26 (Oreo); but we are going to fix that soon.

The github.io page you mentioned is going to be updated soon, sorry about that!

If you keep having issues, you can report them here for now.

Ciao,
Guido

**Comment by djulianrb** [comment]
Hello,
I have a issue, when i going to run DecodeListener example (https://github.com/datalogic/android-samples-astudio)  android studio show me this error: 

pkg: /data/local/tmp/com.datalogic.examples.decodelistener
Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY]
$ adb shell pm uninstall com.datalogic.examples.decodelistener
Unknown failure (Failure)
Error while Installing APK

I follow the documentation https://datalogic.github.io/quick-start/android-studio.html for run the examples,

Could you help me? :s

**Comment by guidodavide** [comment]
Hi djulianrb,

Are you testing your app on a Datalogic device?
In order to run the sample you must have a Datalogic terminal equipped with the "**com.datalogic.device**" library.
The sample's AndroidManifest file requires mandatorily the lib.

On which device are you testing?

**Comment by AdelSari** [comment]
Hi, 
i am testing the SDK within my Android application on the Joya Touch (Android 6) and it works fine, 
When i switch to DL-Axist (Android 4.4), the application crash, the minSDK is set to Api 19, 
i am using datalogic-sdk-v1.7-21
can you help please,
thanks

**Comment by guidodavide** [comment]
Hello AdelSari,
I think you may report this kind of issue to your local technical support of reference.

Anyway, which Firmware release is running your Axist?
Is the Axist updated to Datalogic SDK v1.7 (you can see it in Settings/Device Info.

Which error is reported on logcat whenever your app crashes?

Guido

**Comment by AdelSari** [comment]
Hi guididavide, thanks for your help,
the DL-Axsist is running the firmeware 2.01.36.20170428
for the Datalogic SDK it's 1.4
How can i update it to newer version ?
thanks

**Comment by guidodavide** [comment]
moved on issue [2](https://github.com/datalogic/android-sdk-addon/issues/2)
