### ISSUE TITLE
SDK not found with Gradle V5.4.1

### ISSUE THREAD

**Issue by stepmen** [datalogic/android-sdk-addon#3]
I've done an update of gradle to version 5.4.1 and 
Android gradle from 3.4.2 to 3.5.0 and it's not working : 

I get the following error : 
platform 'Datalogic:Datalogic SDK v1:28' not found.

I Tried to update the sdk same result

**Comment by jsanta65** [comment]
Same issue on my side.

**Comment by stepmen** [comment]
Response from Dtalogic support : 
There is a known bug (at google side) in Android Studio, which prevents the standard Add-On mechanism from running. 
Waiting for a fix by the Android Studio developers, we have to suggest a different compiling approach:

1) change the "compile SDK version" from "the Datalogic Add-On" to any "standard Android SDK"  

e.g :
   compileSdkVersion 28

2) then to add our SDK as a Maven Dependency in this way :
https://datalogic.github.io/quick-start/jitpack-maven.html

e.g.
build.gradle
allprojects { repositories { jcenter() maven { url "https://jitpack.io" } } }

app/build.gradle:
dependencies { implementation 'com.github.datalogic:datalogic-android-sdk:1.12' }

I did it and update to gradle 3.5 and it works

**Comment by jsanta65** [comment]
Confirmed. It works !!  Thanks.

**Comment by acaliaro** [comment]
I have used "maven" but I have this error:

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.datalogic:datalogic-android-sdk:1.21.
     Required by:
         project :app

**Comment by codybrookshear** [comment]
Hi @acaliaro, could you double-check that you did the first step also by adding the jitpack repo as described here?

https://datalogic.github.io/android/overview/#add-jitpackio-repository

**Comment by acaliaro** [comment]
> Hi @acaliaro, could you double-check that you did the first step also by adding the jitpack repo as described here?
> 
> https://datalogic.github.io/android/overview/#add-jitpackio-repository

For me this issue can be closed
